name: nip24
description: This package contains the extra metadata fields that can be added to a Nostr kind 0 event as described in the NIP-24.
version: 0.0.3
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip24

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  nip01: ^0.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
