name: nip47
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  dartstr_utils: ^1.0.0
  nip01: ^1.0.0
  nip04: ^1.0.0
  meta: ^1.15.0
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
